services:

    vidamoto-ghost:
        image: 
            ghost:6.0.5-alpine
        container_name: 
            vidamoto-ghost
        restart: 
            always
        ports:
            - "2369:2368"
        environment:
            - url=${URL}
            - database__client=${DATABASE__CLIENT}
            - database__connection__host=${DATABASE__CONNECTION__HOST}
            - database__connection__user=${DATABASE__CONNECTION__USER}
            - database__connection__password=${DATABASE__CONNECTION__PASSWORD}
            - database__connection__database=${DATABASE__CONNECTION__DATABASE}
        volumes:
            - ./volume/ghost:/var/lib/ghost/content
        networks:
            - x01-net

networks:
    x01-net:
        external: true